---
- name: "Post-installation - Vérification et correction du cluster"
  hosts: masters
  become: true
  tasks:
    - name: "Vérification de l'état des nœuds"
      shell: kubectl get nodes --no-headers | grep -v Ready | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: not_ready_nodes

    - name: "Debug - Nœuds non prêts"
      debug:
        msg: "Nombre de nœuds non prêts: {{ not_ready_nodes.stdout }}"

    - name: "Vérification de l'installation de Flannel"
      shell: kubectl get pods -n kube-flannel --no-headers 2>/dev/null | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: flannel_pods_count
      failed_when: false

    - name: "Force installation de Flannel si absent"
      shell: |
        echo "Installation forcée de Flannel..."
        kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
        sleep 15
        echo "Attente du déploiement de Flannel..."
        kubectl rollout status daemonset/kube-flannel-ds -n kube-flannel --timeout=300s
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: flannel_pods_count.stdout|int == 0
      retries: 2
      delay: 10

    - name: "Attente que les nœuds deviennent Ready"
      shell: kubectl get nodes --no-headers | grep -v NotReady | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: ready_nodes_count
      until: ready_nodes_count.stdout|int >= groups['all']|length
      retries: 20
      delay: 15
      failed_when: false

    - name: "État final des nœuds"
      shell: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: final_nodes_status

    - name: "État final des pods système"
      shell: kubectl get pods -n kube-system -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: final_system_pods

    - name: "État final des pods Flannel"
      shell: kubectl get pods -n kube-flannel -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: final_flannel_pods
      failed_when: false

    - name: "Résultats finaux"
      debug:
        msg: |
          === NŒUDS ===
          {{ final_nodes_status.stdout }}
          
          === PODS SYSTÈME ===
          {{ final_system_pods.stdout }}
          
          === PODS FLANNEL ===
          {{ final_flannel_pods.stdout if final_flannel_pods.rc == 0 else 'Flannel non trouvé' }}