---
- name: "Installation et configuration de containerd"
  tags: containerd
  block:
    - name: "Installation de containerd (version ciblée)"
      apt:
        name: "containerd={{ containerd_version }}"
        state: present

    - name: "Création du répertoire de configuration containerd"
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: "Génération de la configuration par défaut de containerd"
      shell: containerd config default > /etc/containerd/config.toml

    - name: "Configuration de containerd pour utiliser systemd cgroup driver"
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: "Redémarrage et activation de containerd"
      systemd:
        name: containerd
        state: restarted
        enabled: true
        daemon_reload: true

    - name: "Vérification du statut de containerd"
      systemd:
        name: containerd
        state: started

    - name: "Création du répertoire CNI plugins"
      file:
        path: /opt/cni/bin
        state: directory
        mode: '0755'

    - name: "Téléchargement des plugins CNI"
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz"
        dest: "/tmp/cni-plugins-linux-amd64-v1.3.0.tgz"
        timeout: 120
        mode: '0644'
      register: cni_download
      retries: 3
      delay: 5

    - name: "Extraction des plugins CNI"
      unarchive:
        src: "/tmp/cni-plugins-linux-amd64-v1.3.0.tgz"
        dest: "/opt/cni/bin"
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
      when: cni_download is succeeded

    - name: "Vérification de l'installation des plugins CNI"
      stat:
        path: "/opt/cni/bin/loopback"
      register: loopback_plugin

    - name: "Affichage des plugins CNI installés"
      command: ls -la /opt/cni/bin/
      register: cni_plugins_list
      when: loopback_plugin.stat.exists

    - name: "Liste des plugins CNI"
      debug:
        var: cni_plugins_list.stdout_lines
      when: loopback_plugin.stat.exists